import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
// import { Button,EditIcon } from '@/components/mui'
import Layout from '@/components/Layout'
import Heading from "@/components/Heading"
import {AllItems} from "@/lib/hygraph/queries"
// import {
//   Button,
//   List,
//   ListItem,
//   Card,
//   CardMedia,
//   CardContent,
//   CardActions,
//   // Typography
// } from "@/components/mui";

export default function Item({ ssd=[] }) {
  console.log('ssd', ssd)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Item list</Heading>
      </Layout>
    </>
  )
}

export const getStaticProps = async () => {
  const allItems = await fetch(process.env.HYGRAPH_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": `application/json; charset="UTF-8`,
      Authorization: `Bearer ${process.env.HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: AllItems,
    }),
  })
    .then((res) => res.json())
    .catch((err) => console.log(err));
  console.log(allItems);
  const items = allItems.data.items;
  console.log(items);
  return {
    props: {
      ssd: items,
    },
  };
};