import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Markdown from 'marked-react';
import {
  Button,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  Card,
  CardMedia,
  CardContent,
  CardActions,
  // Typography
} from '@/components/mui';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import { AllItems, SinglePost } from '@/lib/hygraph/queries';

export default function SingleItemQuerie({ ssd = {} }) {
  const {
    title,
    body,
    itemImage: { url },
  } = ssd;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Heading component="h2">Single Item</Heading>
        <Card component={'article'} sx={{ width: '100%' }}>
          <CardMedia sx={{ display: 'grid', placeContent: 'center' }}>
            <Image alt={title} src={url} width="200" height="200" />
          </CardMedia>
          <CardContent>
            <Heading component="h2">{title}</Heading>
            <Markdown>{body}</Markdown>
          </CardContent>
        </Card>
      </Layout>
    </>
  );
}

export const getStaticPaths = async () => {
  const allItems = await fetch(process.env.HYGRAPH_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: AllItems,
    }),
  })
    .then((res) => res.json())
    .then((res) => {
      console.log(res.data.items);
      return res.data.items;
    })
    .catch((err) => console.log(err));

  const paths = allItems.map((unit) => ({
    params: { slug: unit.slug },
  }));

  return { paths, fallback: false };
};

export async function getStaticProps({ params }) {
  // console.log(params);
  const { item: unit } = await fetch(process.env.HYGRAPH_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: SinglePost,
      variables: { slug: params.slug },
    }),
  })
    .then((res) => res.json())
    .then((res) => res.data)
    .catch((err) => console.log(err));

  return { props: { ssd: unit } };
}
